// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabWZoROFzSi4DMgnN8QlsIBVbMFEGrsM',
    appId: '1:3971835872:web:68d2b00e2843a1ae606d85',
    messagingSenderId: '3971835872',
    projectId: 'viptaxi-et',
    authDomain: 'viptaxi-et.firebaseapp.com',
    databaseURL: 'https://viptaxi-et-default-rtdb.firebaseio.com',
    storageBucket: 'viptaxi-et.appspot.com',
    measurementId: 'G-1QWT5GW0CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMT2qANAX6Pnx6Ah8bsuQ63p5uajMVvjk',
    appId: '1:3971835872:android:6a2861600db389dc606d85',
    messagingSenderId: '3971835872',
    projectId: 'viptaxi-et',
    databaseURL: 'https://viptaxi-et-default-rtdb.firebaseio.com',
    storageBucket: 'viptaxi-et.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRsZ--YieqQa-a38NlFbaFIwsQGF4TECU',
    appId: '1:3971835872:ios:d8a9ee691022a9b2606d85',
    messagingSenderId: '3971835872',
    projectId: 'viptaxi-et',
    databaseURL: 'https://viptaxi-et-default-rtdb.firebaseio.com',
    storageBucket: 'viptaxi-et.appspot.com',
    iosBundleId: 'org.viptaxi.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRsZ--YieqQa-a38NlFbaFIwsQGF4TECU',
    appId: '1:3971835872:ios:a851bbdf8887b7bd606d85',
    messagingSenderId: '3971835872',
    projectId: 'viptaxi-et',
    databaseURL: 'https://viptaxi-et-default-rtdb.firebaseio.com',
    storageBucket: 'viptaxi-et.appspot.com',
    iosBundleId: 'org.viptaxi.driver.RunnerTests',
  );
}
